### ISSUE TITLE
[📄 Docs] 깃 위키 페이지 세팅하기

### ISSUE THREAD

**Issue by puretension** [puretension/DGU-CSE-Graduation-Verification#1]
## 🛠 Issue

ISSUE & MILESTONE & PROJECT & GIT WIKI
- 본 개별연구가 끝나고도 학생 개개인들의 노력(조사, 구현 등)이 단순 보고서 제출이 아닌 오픈소스처럼 공유된다면 이후의 연구에 도움이 될거라 판단
- ISSUE, MILESTONE을 통한 프로젝트 관리를 통한 문제나 고민, 한계점 을 명확히 기록 후 해결방법 고민일때 면담, 해결해 나가는데 초점(고질 적인 문제들 누적, 해결책 조사, 개선)을 맞출 예정
- 깃허브 위키에 프로젝트 이슈 사항을 기록하고 문서를 공동으로 관리
- 앞으로 업로드할 문서들을 편리하고, 체계적으로 관리하기 위해 메뉴(ex, 프로젝트 소개, 데일리, 회의록 등)를 선정해서 페이지를 세팅

## 📝 To-do

- [x] 다른 개발 위키 페이지 조사하기
- [x]  위키로 관리해야할 대상 선정하기(ex, 졸업요건 고려사항, 구체적인 개발사항 등)
- [x]  각 페이지, 상위 메뉴 이름 등 정하기
- [x]  WIKI Page 작성하기

**Comment by puretension** [comment]
[DGU-CSE-Graduation-Verification-Wiki](https://github.com/puretension/DGU-CSE-Graduation-Verification/wiki)
